/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskRouteImport } from './routes/task'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskIndexRouteImport } from './routes/task.index'
import { Route as TaskArchiveRouteImport } from './routes/task.archive'

const TaskRoute = TaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskIndexRoute = TaskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TaskRoute,
} as any)
const TaskArchiveRoute = TaskArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => TaskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/task': typeof TaskRouteWithChildren
  '/task/archive': typeof TaskArchiveRoute
  '/task/': typeof TaskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/task/archive': typeof TaskArchiveRoute
  '/task': typeof TaskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/task': typeof TaskRouteWithChildren
  '/task/archive': typeof TaskArchiveRoute
  '/task/': typeof TaskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/task' | '/task/archive' | '/task/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/task/archive' | '/task'
  id: '__root__' | '/' | '/task' | '/task/archive' | '/task/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaskRoute: typeof TaskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/': {
      id: '/task/'
      path: '/'
      fullPath: '/task/'
      preLoaderRoute: typeof TaskIndexRouteImport
      parentRoute: typeof TaskRoute
    }
    '/task/archive': {
      id: '/task/archive'
      path: '/archive'
      fullPath: '/task/archive'
      preLoaderRoute: typeof TaskArchiveRouteImport
      parentRoute: typeof TaskRoute
    }
  }
}

interface TaskRouteChildren {
  TaskArchiveRoute: typeof TaskArchiveRoute
  TaskIndexRoute: typeof TaskIndexRoute
}

const TaskRouteChildren: TaskRouteChildren = {
  TaskArchiveRoute: TaskArchiveRoute,
  TaskIndexRoute: TaskIndexRoute,
}

const TaskRouteWithChildren = TaskRoute._addFileChildren(TaskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaskRoute: TaskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
